### ISSUE TITLE
Will it be created?

### ISSUE THREAD

**Issue by Obsttube** [paragonie/node-halite#1]
Hello, I have php halite and was looking for node-halite. Will you ever finish node project, or it is cancelled?

**Comment by paragonie-scott** [comment]
We plan on finishing the Node.js implementation of Halite as soon as we can.

However, our top priority is to finish work for paying clients, and thus far, none of our clients are paying us to ensure node-halite is completed, so I'm afraid it must take a back seat.

**Comment by Obsttube** [comment]
Thanks for resp, no problem, I understand.
